const FETCH_ALL = "FETCH_ALL_";
const FETCH_BY_ID = "FETCH_BY_ID_"
const UPDATE = 'UPDATE_';
const DELETE = 'DELETE_';
const CREATE = 'CREATE_';

export const CREATE_EXPERT = `${CREATE}EXPERT`;
export const UPDATE_EXPERT = `${UPDATE}EXPERT`
export const DELETE_EXPERT = `${DELETE}EXPERT`
export const FETCH_ALL_EXPERTS = `${FETCH_ALL}EXPERT`
export const FETCH_EXPERT_BY_ID = `${FETCH_BY_ID}EXPERT`

export const CREATE_CATEGORY = `${CREATE}EXPERT`;
export const UPDATE_CATEGORY = `${UPDATE}EXPERT`
export const DELETE_CATEGORY = `${DELETE}EXPERT`
export const FETCH_ALL_CATEGORY = `${FETCH_ALL}EXPERT`

export const FETCH_APPOINTMENTS_BY_EXPERT = `${FETCH_ALL}APPOINTMENT`
export const FETCH_APPOINTMENT_BY_ID = `${FETCH_BY_ID}APPOINTMENT`
export const CREATE_APPOINTMENT = `${CREATE}APPOINTMENT`
export const DELETE_APPOINTMENT = `${DELETE}APPOINTMENT`

export const CREATE_CALENDAR = `${CREATE}CALENDAR`;
export const UPDATE_CALENDAR = `${UPDATE}CALENDAR`
export const DELETE_CALENDAR = `${DELETE}CALENDAR`
export const FETCH_ALL_CALENDAR = `${FETCH_ALL}CALENDAR`
export const FETCH_CALENDAR_BY_ID = `${FETCH_BY_ID}CALENDAR`
export const FETCH_CALENDAR_BY_EXPERT_ID = `${FETCH_BY_ID}EXPERT_CALENDAR`



export const TOKEN = "TOKEN";
export const EMAIL = "EMAIL"
export const LOGOUT = 'LOGOUT';
export const COOKIE = "cybercity-auth"